
CREATE table user_lab_allowance  (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  version         INT,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  lab_number INT          NOT NULL CHECK (lab_number in (1, 2, 3)),
  /**
  *Блок ключей
  */
  CONSTRAINT fk_user_lab_allowance UNIQUE (user_id, lab_number)
);

CREATE INDEX ix_user_lab_allowance
  ON user_lab_allowance (user_id);

COMMENT ON TABLE user_lab_allowance IS 'Допуск студентов к лабораторным';
COMMENT ON COLUMN user_lab_allowance.version IS 'Версия изменений(контроль одновременного доступа)';
COMMENT ON COLUMN user_lab_allowance.user_id IS 'Идентификатор пользователя';
COMMENT ON COLUMN user_lab_allowance.lab_number IS 'Номер лабораторной';