CREATE TABLE users (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  version     INT,
  login       VARCHAR(256) NOT NULL,
  first_name  VARCHAR(256),
  last_name   VARCHAR(256),
  middle_name VARCHAR(256),
  note        VARCHAR(256),
  password    VARCHAR(256),
  enabled     BOOLEAN      NOT NULL
);

CREATE UNIQUE INDEX ix_users
  ON users (id);

CREATE TABLE authorities (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  version   INT,
  user_id   BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  authority VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX ix_authorities
  ON authorities (id);

CREATE UNIQUE INDEX ix_auth_username
  ON authorities (user_id, authority);

CREATE TABLE groups (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  group_name VARCHAR_IGNORECASE(50) NOT NULL
);

CREATE UNIQUE INDEX ix_groups
  ON groups (id);

CREATE TABLE group_authorities (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  group_id  BIGINT      NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  authority VARCHAR(50) NOT NULL,
  CONSTRAINT fk_group_authorities_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE UNIQUE INDEX ix_group_authorities
  ON group_authorities (id);

CREATE TABLE group_members (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  user_id  BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  group_id BIGINT NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE UNIQUE INDEX ix_group_members
  ON group_members (id);

CREATE TABLE persistent_logins (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  user_id   BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  series    VARCHAR(64),
  token     VARCHAR(64) NOT NULL,
  last_used TIMESTAMP   NOT NULL
);

CREATE UNIQUE INDEX ix_persistent_logins
  ON persistent_logins (id);
