CREATE TABLE lab3data (
  /**
  *Блок системных свойств
  */
  id BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  save_date TIMESTAMP NOT NULL ,
  version INT,
  /**
  *Блок свойств лабы
  */
  tpp_output INT,
  /*number_of_units
  *city*/
  steam_production_capacity INT,
  /*number_of_stacks*/
  stacks_height INT,
  stacks_diameter INT,
  /*wind_direction*/
  wind_speed DOUBLE,
  low_heat_value DOUBLE,
  fuel_consumer DOUBLE,
  carbon_in_fly_ash DOUBLE,
  sulphur_content DOUBLE,
  ash_content DOUBLE,
  water_content DOUBLE,
  ash_recycling_factor DOUBLE,
  flue_gas_nox_concentration DOUBLE,
  stack_exit_temperature INT,
  outside_air_temperature INT,
  excess_air_ratio DOUBLE,
  combustion_product_volume DOUBLE,
  water_vapor_volume DOUBLE,
  air_volume DOUBLE,
  no2_background_concentration DOUBLE,
  no_background_concentration DOUBLE,
  so2_background_concentration DOUBLE,
  ash_background_concentration DOUBLE,
  sulphur_oxides_fraction_associated_by_fly_ash DOUBLE,
  sulphur_oxides_fraction_associated_in_wet_dust_collector DOUBLE,
  sulphur_oxides_fraction_associated_in_desulphurization_system DOUBLE,
  desulphurization_system_running_time DOUBLE,
  boiler_running_time DOUBLE,
  ash_proportion_entrained_gases DOUBLE,
  solid_particles_propotion_collected_in_ash DOUBLE,
  stack_average_gases_speed DOUBLE,
  nox_massive_injection DOUBLE,
  no2_massive_injection DOUBLE,
  no_massive_injection DOUBLE,
  so2_massive_injection DOUBLE,
  ash_massive_injection DOUBLE,
  temperature_coefficient DOUBLE,
  terrain_coefficient DOUBLE,
  harmful_substances_deposition_coefficient DOUBLE,
  no2_mac DOUBLE,
  no_mac DOUBLE,
  so2_mac DOUBLE,
  ash_mac DOUBLE,
  breakdown_wind_speed DOUBLE,
  bwd_no2_ground_level_concentration DOUBLE,
  bwd_no_ground_level_concentration DOUBLE,
  bwd_so2_ground_level_concentration DOUBLE,
  bwd_ash_ground_level_concentration DOUBLE,
  no2_and_so2_summation_group DOUBLE,
  no_and_so2_summation_group DOUBLE,
  bwd_max_ground_level_concentration_distance DOUBLE,
  wind_speed_max_no2_ground_level_concentration DOUBLE,
  wind_speed_max_no_ground_level_concentration DOUBLE,
  wind_speed_max_so2_ground_level_concentration DOUBLE,
  wind_speed_max_ash_ground_level_concentration DOUBLE,
  wind_speed_max_ground_level_concentration_distance DOUBLE,
  /**
  *Блок ключей
  */
  CONSTRAINT fk_lab3data_user FOREIGN KEY (user_id) REFERENCES users (id)
);

/*
* Создадим индексы
*/
CREATE UNIQUE INDEX ix_lab3data_id ON lab3data (id);
CREATE UNIQUE INDEX ix_lab3data_user_id ON lab3data (user_id);

/*
* Добавим комментарии
*/
COMMENT ON COLUMN lab3data.tpp_output IS 'Мощность ГРЭС';
/*COMMENT ON COLUMN lab3data.number_of_units IS 'Число блоков';
*COMMENT ON COLUMN lab3data.city IS 'Район расположения ГРЭС (город)';*/
COMMENT ON COLUMN lab3data.steam_production_capacity IS 'Номинальная паропроизводительность одного котла';
/*COMMENT ON COLUMN lab3data.number_of_stacks IS 'Число дымовых труб';*/
COMMENT ON COLUMN lab3data.stacks_height IS 'Высота дымовой трубы';
COMMENT ON COLUMN lab3data.stacks_diameter IS 'Диаметр устья дымовой трубы';
/*COMMENT ON COLUMN lab3data.wind_direction IS 'Расчетное направление ветра';*/
COMMENT ON COLUMN lab3data.wind_speed IS 'Расчетная скорость ветра';
COMMENT ON COLUMN lab3data.low_heat_value IS 'Низшая теплота сгорания топлива';
COMMENT ON COLUMN lab3data.fuel_consumer IS 'Расход топлива на 1 блок';
COMMENT ON COLUMN lab3data.carbon_in_fly_ash IS 'Потери тепла от механической неполноты сгорания топлива';
COMMENT ON COLUMN lab3data.sulphur_content IS 'Содержание серы в топливе';
COMMENT ON COLUMN lab3data.ash_content IS 'Зольность топлива';
COMMENT ON COLUMN lab3data.water_content IS 'Влажность топлива';
COMMENT ON COLUMN lab3data.ash_recycling_factor IS 'Степень улавливания золы';
COMMENT ON COLUMN lab3data.flue_gas_nox_concentration IS 'Концентрация оксидов азота в сухих газах';
COMMENT ON COLUMN lab3data.stack_exit_temperature IS 'Температура газов на выходе из дымовой трубы';
COMMENT ON COLUMN lab3data.outside_air_temperature IS 'Температура наружного воздуха';
COMMENT ON COLUMN lab3data.excess_air_ratio IS 'Коэффициент избытка воздуха в уходящих газах';
COMMENT ON COLUMN lab3data.combustion_product_volume IS 'Теоретический объем продуктов сгорания';
COMMENT ON COLUMN lab3data.water_vapor_volume IS 'Теоретический объем паров воды';
COMMENT ON COLUMN lab3data.air_volume IS 'Теоретический объем воздуха';
COMMENT ON COLUMN lab3data.no2_background_concentration IS 'Фоновая концентрация NO2';
COMMENT ON COLUMN lab3data.no_background_concentration IS 'Фоновая концентрация NO';
COMMENT ON COLUMN lab3data.so2_background_concentration IS 'Фоновая концентрация SO2';
COMMENT ON COLUMN lab3data.ash_background_concentration IS 'Фоновая концентрация золы';
COMMENT ON COLUMN lab3data.sulphur_oxides_fraction_associated_by_fly_ash IS 'Доля оксидов серы, связываемых летучей золой в котле';
COMMENT ON COLUMN lab3data.sulphur_oxides_fraction_associated_in_wet_dust_collector IS 'Доля оксидов серы, улавливаемых в мокром золоуловителе попутно с твердыми частицами';
COMMENT ON COLUMN lab3data.sulphur_oxides_fraction_associated_in_desulphurization_system IS 'Доля оксидов серы, улавливаемых в сероулавливающей установке';
COMMENT ON COLUMN lab3data.desulphurization_system_running_time IS 'Длительность работы сероулавливающей установки';
COMMENT ON COLUMN lab3data.boiler_running_time IS 'Длительность работы котла';
COMMENT ON COLUMN lab3data.ash_proportion_entrained_gases IS 'Доля золы, уносимой газами из котла';
COMMENT ON COLUMN lab3data.solid_particles_propotion_collected_in_ash IS 'Доля твердых частиц, улавливаемых в золоуловителях';
COMMENT ON COLUMN lab3data.stack_average_gases_speed IS 'Средняя скорость газов на выходе из дымовой трубы';
COMMENT ON COLUMN lab3data.nox_massive_injection IS 'Суммарное количество NOx поступающего в атмосферу с дымовыми газами';
COMMENT ON COLUMN lab3data.no2_massive_injection IS 'Суммарное количество NO2, поступающего в атмосферу с дымовыми газами';
COMMENT ON COLUMN lab3data.no_massive_injection IS 'Суммарное количество NO, поступающего в атмосферу с дымовыми газами';
COMMENT ON COLUMN lab3data.so2_massive_injection IS 'Суммарное количество SO2, поступающего в атмосферу с дымовыми газами';
COMMENT ON COLUMN lab3data.ash_massive_injection IS 'Суммарное количество золы, поступающей в атмосферу с дымовыми газами';
COMMENT ON COLUMN lab3data.temperature_coefficient IS 'Коэффициент, характеризующий температурную стратификацию атмосферы';
COMMENT ON COLUMN lab3data.terrain_coefficient IS 'Коэффициент, учитывающий влияние рельефа местности';
COMMENT ON COLUMN lab3data.harmful_substances_deposition_coefficient IS 'Безразмерный коэффициент, учитывающий скорость оседания вредных веществ в атмосферном воздухе';
COMMENT ON COLUMN lab3data.no2_mac IS 'ПДК NO2';
COMMENT ON COLUMN lab3data.no_mac IS 'ПДК NO';
COMMENT ON COLUMN lab3data.so2_mac IS 'ПДК SO2';
COMMENT ON COLUMN lab3data.ash_mac IS 'ПДК золы';
COMMENT ON COLUMN lab3data.breakdown_wind_speed IS 'Опасная скорость ветра';
COMMENT ON COLUMN lab3data.bwd_no2_ground_level_concentration IS 'Максимальное значение приземной концентрации NO2 при опасной скорости ветра';
COMMENT ON COLUMN lab3data.bwd_no_ground_level_concentration IS 'Максимальное значение приземной концентрации NO при опасной скорости ветра';
COMMENT ON COLUMN lab3data.bwd_so2_ground_level_concentration IS 'Максимальное значение приземной концентрации SO2 при опасной скорости ветра';
COMMENT ON COLUMN lab3data.bwd_ash_ground_level_concentration IS 'Максимальное значение приземной концентрации золы при опасной скорости ветра';
COMMENT ON COLUMN lab3data.no2_and_so2_summation_group IS 'Безразмерная концентрация веществ, обладающих суммацией вредного действия (NO2 и SO2)';
COMMENT ON COLUMN lab3data.no_and_so2_summation_group IS 'Безразмерная концентрация веществ, обладающих суммацией вредного действия (NO и SO2)';
COMMENT ON COLUMN lab3data.bwd_max_ground_level_concentration_distance IS 'Расстояние от источника выбросов, на котором приземные концентрации загрязняющих веществ';
COMMENT ON COLUMN lab3data.wind_speed_max_no2_ground_level_concentration IS 'Максимальное значение приземной концентрации NO2 при расчетной скорости ветра';
COMMENT ON COLUMN lab3data.wind_speed_max_no_ground_level_concentration IS 'Максимальное значение приземной концентрации NO при расчетной скорости ветра';
COMMENT ON COLUMN lab3data.wind_speed_max_so2_ground_level_concentration IS 'Максимальное значение приземной концентрации SO2 при расчетной скорости ветра';
COMMENT ON COLUMN lab3data.wind_speed_max_ash_ground_level_concentration IS 'Максимальное значение приземной концентрации золы при расчетной скорости ветра';
COMMENT ON COLUMN lab3data.wind_speed_max_ground_level_concentration_distance IS 'Расстояние от источника выброса, на котором при скорости ветра u приземная концентрация вредных веществ достигает максимального значения';