CREATE TABLE lab1data (
  /**
  *Блок системных свойств
  */
  id                                        BIGINT             GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  user_id                                   BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  start_date                                TIMESTAMP NOT NULL,
  save_date                                 TIMESTAMP NOT NULL,
  version                                   INT,
  completed                                 BOOLEAN   NOT NULL DEFAULT FALSE,

  /**
  *Блок свойств лабы
  */
  name                                      VARCHAR(256),
  excess_Air_Ratio                          DOUBLE,
  flue_Gas_NOx_Concentration_NC             DOUBLE,
  excess_Of_Norms                           BOOLEAN,
  flue_Gases_Rate                           DOUBLE,
  dry_Gases_Flow_Rate                       DOUBLE,
  mass_Emissions                            DOUBLE,
  flue_Gases_Speed                          DOUBLE,
  f                                         DOUBLE,
  m                                         DOUBLE,
  u                                         DOUBLE,
  n                                         DOUBLE,
  d                                         DOUBLE,
  harmful_Substances_Deposition_Coefficient DOUBLE,
  terrain_Coefficient                       DOUBLE,
  temperature_Coefficient                   DOUBLE,
  distance_From_Emission_Source             DOUBLE,
  maximum_Surface_Concentration             DOUBLE,
  /**
  *Блок ключей
  */
  CONSTRAINT fk_LAB1DATA_user FOREIGN KEY (user_id) REFERENCES users (id)
);

/*
* Создадим индексы
*/
CREATE UNIQUE INDEX ix_lab1data_id
  ON lab1data (id);
CREATE INDEX ix_LAB1DATA_user_id
  ON lab1data (user_id);
CREATE INDEX ix_LAB1DATA_user_id_start_date
  ON lab1data (USER_ID, START_DATE);

/*
* Добавим комментарии
*/
COMMENT ON TABLE LAB1DATA IS 'Данные лабораторной №1';
COMMENT ON COLUMN LAB1DATA.id IS 'Уникальный идентификатор выполненного варианта';
COMMENT ON COLUMN LAB1DATA.user_id IS 'ID пользователя, выполнившего задание';
COMMENT ON COLUMN LAB1DATA.start_date IS 'Дата и время начала выполнения лабораторной';
COMMENT ON COLUMN LAB1DATA.save_date IS 'Дата и время последнего сохранения результатов';
COMMENT ON COLUMN LAB1DATA.version IS 'Версия изменений(контроль одновременного доступа)';
COMMENT ON COLUMN LAB1DATA.completed IS 'Признак завершенности лабораторной работы';

COMMENT ON COLUMN LAB1DATA.excess_air_ratio IS 'Коэффициент избытка воздуха в уходящих газах';
COMMENT ON COLUMN LAB1DATA.temperature_coefficient IS 'Коэффициент, характеризующий температурную стратификацию атмосферы';
COMMENT ON COLUMN LAB1DATA.terrain_coefficient IS 'Коэффициент, учитывающий влияние рельефа местности';
COMMENT ON COLUMN LAB1DATA.harmful_substances_deposition_coefficient IS 'Безразмерный коэффициент, учитывающий скорость оседания вредных веществ в атмосферном воздухе';
COMMENT ON COLUMN LAB1DATA.name IS 'Название объекта';
COMMENT ON COLUMN LAB1DATA.flue_Gas_NOx_Concentration_NC IS 'Концентрация оксидов азота, приведенная к стандартному коэффициенту избытка воздуха α=1,4';
COMMENT ON COLUMN LAB1DATA.excess_Of_Norms IS 'Превышение допустимых норм';
COMMENT ON COLUMN LAB1DATA.flue_Gases_Rate IS 'Расход дымовых газов, выбрасываемых в атмосферу';
COMMENT ON COLUMN LAB1DATA.dry_Gases_Flow_Rate IS 'Объемный расход сухих газов';
COMMENT ON COLUMN LAB1DATA.mass_Emissions IS 'Массовые выбросы оксидов азота';
COMMENT ON COLUMN LAB1DATA.flue_Gases_Speed IS 'Скорость дымовых газов на выходе из дымовой трубы';
COMMENT ON COLUMN LAB1DATA.f IS 'Параметр f';
COMMENT ON COLUMN LAB1DATA.m IS 'Коэффициент m учитывающий условия выхода газов из дымовой трубы';
COMMENT ON COLUMN LAB1DATA.u IS 'Параметр υ_м';
COMMENT ON COLUMN LAB1DATA.n IS 'Коэффициент n учитывающий условия выхода газов из дымовой трубы';
COMMENT ON COLUMN LAB1DATA.d IS 'Безразмерный коэффициент d';
COMMENT ON COLUMN LAB1DATA.distance_From_Emission_Source IS 'Расстояние от источника выбросов, на котором приземные концентрации загрязняющих веществ достигают максимального значения';
COMMENT ON COLUMN LAB1DATA.maximum_Surface_Concentration IS 'Максимальная приземная концентрация оксидов азота';

CREATE TABLE lab1variant (
  id                           BIGINT IDENTITY PRIMARY KEY REFERENCES LAB1DATA (id) ON DELETE CASCADE,
  version                      INT,
  /**
  *Блок свойств лабы
  */
  name                                      VARCHAR(256),
  outside_Air_Temperature                   INT,
  stacks_Height                             DOUBLE,
  stacks_Diameter                           DOUBLE,
  time                                      TIMESTAMP,
  steam_Production_Capacity                 INT,
  oxygen_Concentration_Point                DOUBLE,
  fuel_Consumer                             INT,
  stack_Exit_Temperature                    INT,
  flue_Gas_NOx_Concentration                INT,
  is_experiment                             BOOL NOT NULL DEFAULT FALSE
);

/*
* Создадим индексы
*/
CREATE UNIQUE INDEX ix_lab1variant_id
  ON lab1variant (id);

/*
* Добавим комментарии
*/
COMMENT ON TABLE lab1variant IS 'Вариант лабораторной №1';
COMMENT ON COLUMN lab1variant.stacks_height IS 'Высота дымовой трубы';
COMMENT ON COLUMN lab1variant.stacks_diameter IS 'Диаметр устья дымовой трубы';
COMMENT ON COLUMN lab1variant.flue_gas_nox_concentration IS 'Концентрация оксидов азота в сухих газах';
COMMENT ON COLUMN lab1variant.stack_exit_temperature IS 'Температура газов на выходе из дымовой трубы';
COMMENT ON COLUMN lab1variant.outside_air_temperature IS 'Температура наружного воздуха';
COMMENT ON COLUMN lab1variant.name IS 'Название объекта';
COMMENT ON COLUMN lab1variant.steam_Production_Capacity IS 'Паровая нагрузка котла';
COMMENT ON COLUMN lab1variant.oxygen_Concentration_Point IS 'Содержание кислорода в сечении газохода, где проводились измерения';
COMMENT ON COLUMN lab1variant.is_experiment IS 'Работа выполняется на основании эксперимента';

