CREATE TABLE lab_test_question (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  version         INT,
  lab_number      INT          NOT NULL,
  question_title  VARCHAR(256) NOT NULL,
  question_number INT          NOT NULL,

  /**
  *Блок ключей
  */
  CONSTRAINT fk_lab_test_data_variant UNIQUE (question_number, lab_number)
);

COMMENT ON TABLE lab_test_question IS 'Тестовые вопросы для лабораторной';
COMMENT ON COLUMN lab_test_question.id IS 'Уникальный идентификатор вопроса';
COMMENT ON COLUMN lab_test_question.version IS 'Версия изменений(контроль одновременного доступа)';
COMMENT ON COLUMN lab_test_question.question_title IS 'Название вопроса';
COMMENT ON COLUMN lab_test_question.question_number IS 'Номер вопроса';
COMMENT ON COLUMN lab_test_question.lab_number IS 'Номер лабораторной';

CREATE TABLE lab_test_question_variant (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  version                INT,
  question_id            BIGINT       NOT NULL REFERENCES lab_test_question (id) ON DELETE CASCADE,
  image                  VARCHAR(256),
  question_text          VARCHAR(1024) NOT NULL,
  question_variant       INT          NOT NULL,
  answers                ARRAY        NOT NULL,
  question_answer_number INT          NOT NULL
);

COMMENT ON TABLE lab_test_question_variant IS 'Варианты вопросов для лабораторной';
COMMENT ON COLUMN lab_test_question_variant.id IS 'Уникальный идентификатор варианта';
COMMENT ON COLUMN lab_test_question_variant.version IS 'Версия изменений(контроль одновременного доступа)';
COMMENT ON COLUMN lab_test_question_variant.image IS 'Название файла с изображением для теста';
COMMENT ON COLUMN lab_test_question_variant.question_variant IS 'Вариант вопроса';
COMMENT ON COLUMN lab_test_question_variant.question_text IS 'Текст вопроса';
COMMENT ON COLUMN lab_test_question_variant.answers IS 'Варианты ответов';
COMMENT ON COLUMN lab_test_question_variant.question_answer_number IS 'Верный номер ответа на вопрос';

CREATE TABLE lab_test_home_work_question (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  version          INT,
  question_id      BIGINT       NOT NULL REFERENCES lab_test_question (id) ON DELETE CASCADE,
  image            VARCHAR(256),
  question_text    VARCHAR(1024) NOT NULL,
  question_variant INT          NOT NULL,
  value_type       VARCHAR(32)  NOT NULL,
  dimension        VARCHAR(8),
  formulae         VARCHAR(4000),
);

COMMENT ON TABLE lab_test_home_work_question IS 'Варианты тестовых вопросов для домашнего задания';
COMMENT ON COLUMN lab_test_home_work_question.id IS 'Уникальный идентификатор варианта';
COMMENT ON COLUMN lab_test_home_work_question.version IS 'Версия изменений(контроль одновременного доступа)';
COMMENT ON COLUMN lab_test_home_work_question.image IS 'Название файла с изображением для теста';
COMMENT ON COLUMN lab_test_home_work_question.question_text IS 'Текст вопроса';
COMMENT ON COLUMN lab_test_home_work_question.question_variant IS 'Вариант вопроса';
COMMENT ON COLUMN lab_test_home_work_question.value_type IS 'Тип проверяемого значения';
COMMENT ON COLUMN lab_test_home_work_question.dimension IS 'Размерность';
COMMENT ON COLUMN lab_test_home_work_question.formulae IS 'Формула, записанная в JavaScript нотации. ' ||
                                                          'Названия переменных в формуле должны совпадать с названиями полей в лабораторной';
