CREATE TABLE user_test_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 0) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  lab_number int not null,
  last_modify_date timestamp not null,
  point_count int not null,
  mark int not null,
  version INT,
  /**
  *Блок ключей
  */
  CONSTRAINT fk_user_test_history_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_user_test_history UNIQUE (user_id, lab_number)
);

CREATE INDEX ix_user_test_history
  ON user_test_history (user_id, lab_number);

COMMENT ON TABLE user_test_history IS 'Выполненные пользователями тесты';
COMMENT ON COLUMN user_test_history.id IS 'Уникальный идентификатор теста';
COMMENT ON COLUMN user_test_history.version IS 'Версия изменений(контроль одновременного доступа)';
COMMENT ON COLUMN user_test_history.user_id IS 'Идентификатор пользователя';
COMMENT ON COLUMN user_test_history.lab_number IS 'Номер лабораторной';
COMMENT ON COLUMN user_test_history.mark IS 'Оценка';
COMMENT ON COLUMN user_test_history.point_count IS 'Количество баллов';