
ALTER TABLE lab1data ALTER COLUMN start_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lab1data ALTER COLUMN save_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lab2data ALTER COLUMN start_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lab2data ALTER COLUMN save_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lab3data ALTER COLUMN start_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE lab3data ALTER COLUMN save_date SET DEFAULT CURRENT_TIMESTAMP;