ALTER TABLE STUDY_TEAMS ADD NAME_NEW VARCHAR(256);

update STUDY_TEAMS set NAME_NEW = NAME;

drop index IX_STUDY_TEAMS;

ALTER TABLE STUDY_TEAMS drop NAME;


ALTER TABLE STUDY_TEAMS alter column NAME_NEW rename to NAME ;

CREATE UNIQUE INDEX IX_STUDY_TEAMS
  ON STUDY_TEAMS (name, group_id);

ALTER TABLE STUDY_TEAMS ALTER COLUMN NAME SET NOT NULL;

